version: 2
workflows:
  version: 2
  build:
    jobs:
      -docker:
      - image: circleci/node:10.8.0

    steps:
      - checkout

      - run:
          name: yarn install
          command: |
            yarn install

      - run:
          name: Build
          command: |
            yarn tsc

      - run:
          name: Lint
          command: |
            yarn tslint

      - run:
          name: Test
          command: |
            yarn test
