// extract strings to locize/i18n setup
export const presets = {
  butterWaterRatio: 0.15,
  eggWaterPercentage: 0.76,
  flourIncrementAmount: 50,
  flourWeightPresets: [500, 1000, 1500, 2000, 3000],
  initialFlourValue: 1000,
  initialLeavenHydration: 100,
  initialLeavenValue: 200,
  initialTargetDoughWeight: 1000,
  initialTargetHydration: 75,
  initialTargetInoculation: 20,
  initialWaterValue: 725,
  languageConstants: {
    _current_inoculation: 'Current Inoculation',
    _final_volume: 'Final Volume (Experimental)',
    _flour_weight: 'Flour',
    _gram_abbvr: 'g',
    _initial_volume: 'Initial Volume (Experimental)',
    _inoculation: 'Target Inoculation',
    _leaven_hydration: 'Leaven Hydration',
    _leaven_weight: 'Leaven',
    _liter_abbvr: 'lt',
    _percent: '%',
    _recipe_flour: 'Recipe Flour',
    _recipe_water: 'Recipe Water',
    _recommended_salt: 'Recommended Salt',
    _reset: 'Pull to load recipe...',
    _target_dough_weight: 'Target Dough Weight',
    _target_hydration: 'Target Hydration',
    _target_inoculation: 'Target Inoculation',
    _total_baked_weight: 'Total Baked Weight',
    _total_dough_weight: 'Total Dough Weight',
    _total_flour: 'Total Flour',
    _total_hydration: 'Total Hydration',
    _total_leaven: 'Leaven',
    _total_water: 'Total Water',
    _water: 'Water'
  },
  leavenHydrationIncrementAmount: 5,
  leavenHydrationPresets: [50, 75, 100, 125, 150, 175],
  leavenInoculationPresets: [10, 15, 20, 25, 30, 35, 50],
  leavenWeightIncrementAmount: 25,
  maxFlour: 10000,
  maxLeaven: 5000,
  maxLeavenHydration: 200,
  maxTargetHydration: 200,
  maxWater: 10000,
  milkWaterPercentage: 0.87,
  minFlour: 0,
  minLeaven: 0,
  minLeavenHydration: 0,
  minTargetHydration: 0,
  minWater: 0,
  postBakeWeightRatio: 0.85,
  saltRatio: 0.022,
  storageKey: 'persistenceModel',
  targetHydrationIncrementAmount: 1,
  targetHydrationPresets: [50, 75, 80, 85, 90, 95],
  waterIncrementAmount: 25
};
