export const presets = {
  desiredHydrationPresets: [50, 75, 80, 85, 90, 95],
  desiredTargetHydrationIncrementAmount: 1,
  flourIncrementAmount: 50,
  flourWeightPresets: [1000, 1500, 2000, 3000, 5000],
  initialDesiredTargetHydration: 75,
  initialFlourWeight: 1000,
  initialLeavenHydratioon: 100,
  initialLeavenWeight: 200,
  initialWaterWeight: 725,
  languageConstants: {
    _appTitle: '@sourdoughpie hydration app',
    _flour_weight: 'Flour',
    _gram_abbvr: 'g',
    _leaven_hydration: 'Leaven Hydration',
    _leaven_weight: 'Leaven',
    _liter_abbvr: 'lt',
    _percent: '%',
    _target_dough_weight: 'Target Dough Weight',
    _target_hydration: 'Target Hydration',
    _water: 'Water'
  },
  leavenHydrationIncrementAmount: 5,
  leavenHydrationPresets: [50, 75, 100, 125, 150, 175],
  leavenInoculationPresets: [15, 20, 25, 30, 35, 50],
  leavenWeightIncrementAmount: 25,
  maxDesiredHydration: 200,
  maxFlour: 10000,
  maxLeaven: 5000,
  maxLeavenHydration: 200,
  maxWater: 10000,
  minDesiredHydration: 0,
  minFlour: 0,
  minLeaven: 0,
  minLeavenHydration: 0,
  minWater: 0,
  postBakeWeightRatio: 0.85,
  saltRatio: 0.022,
  waterIncrementAmount: 25
};
